fix: use %h/.local/bin/polybar-launch
Change-Id: Iac105d882046a3fe2cd03dad5a0024f27f551567
GitOrigin-RevId: bec953fb6f83779ec5f3540f4dd6b82464256bb6

diff --git a/polybar/.local/bin/polybar-launch b/polybar/.local/bin/polybar-launch
--- a/polybar/.local/bin/polybar-launch
+++ b/polybar/.local/bin/polybar-launch
@@ -1,7 +1,9 @@
 #!/usr/bin/env sh
 
-if mon=$(xrandr --query | grep "connected primary" | cut -d " " -f 1 2>/dev/null); then
-    MONITOR=$mon polybar --reload top &
+if MONITOR=$(xrandr --query | awk '/connected primary/ {print $1}' 2>/dev/null); then
+    echo "using display: ${MONITOR}"
+    MONITOR="$MONITOR" polybar --reload top
 else
-    polybar --reload top &
+    echo "failed to detect primary monitor"
+    exit 1
 fi
